### ISSUE TITLE
com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.lang.String, and MIME media type, application/json, was not found

### ISSUE THREAD

**Issue by farmazon3000** [karussell/directions-api-vrp-java-client#9]
When I call example on Android [TSP_BiggestCitiesInGermanyByBikeExample](https://github.com/karussell/directions-api-vrp-java-client/blob/master/src/main/java/com/graphhopper/api/vrp/example/TSP_BiggestCitiesInGermanyByBikeExample.java):

```
private void start() throws Exception {

        Request request = createRequest();
        VrpApi vrpApi = new VrpApi();

        // enable debugging for sending and receiving requests
        // ApiClient client = new ApiClient().setDebugging(true);
        // api.setApiClient(client);

        String key = "...";
        JobId jobId = vrpApi.postVrp(key, request);

        System.out.println(jobId.getJobId());

        SolutionApi solApi = new SolutionApi();
        Response rsp;

        while (true) {
            rsp = solApi.getSolution(key, jobId.getJobId());
            if (rsp.getStatus().equals(Response.StatusEnum.FINISHED)) {
                break;
            }
            Thread.sleep(200);
        }
        System.out.println(rsp);

    }

    private Request createRequest() {
        Request request = new Request();
        request.setAlgorithm(new Algorithm());
        /*
        specify vehicles
         */
        List<Vehicle> vehicles = new ArrayList<Vehicle>();

        Vehicle v = new Vehicle();
        v.setVehicleId("v1");
        v.setStartAddress(createAddress("berlin", 52.537, 13.406));
        v.setTypeId("my-awesome-bike");
        vehicles.add(v);
        request.setVehicles(vehicles);

        /*
        specify vehicle type
         */
        List<VehicleType> types = new ArrayList<VehicleType>();
        VehicleType type = new VehicleType();
        type.setProfile(VehicleType.ProfileEnum.BIKE);
        type.setTypeId("my-awesome-bike");
        types.add(type);
        request.setVehicleTypes(types);

        /*
        specify your services
         */
        List<Service> services = new ArrayList<Service>();

        services.add(createService("hamburg", 53.552, 9.999));
        services.add(createService("munich", 48.145, 11.570));
        services.add(createService("cologne", 50.936, 6.957));
        services.add(createService("frankfurt", 50.109, 8.670));

        request.setServices(services);

        return request;
    }

    public Address createAddress(String locationId, double lat, double lon) {
        Address a = new Address();
        a.setLat(lat);
        a.setLon(lon);
        a.setLocationId(locationId);
        return a;
    }

    public Service createService(String id, double lat, double lon) {
        Service service = new Service();
        service.setId(id);
        service.setType(Service.TypeEnum.SERVICE);
        service.setAddress(createAddress(id, lat, lon));
        return service;
    }
```

With dependencies

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.graphhopper:directions-api-java-client:0.5.0.2'
    compile 'com.graphhopper:directions-api-vrp-java-client:0.5.0.1'
}
```

I'm getting exception

```
 com.sun.jersey.api.client.ClientHandlerException: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.lang.String, and MIME media type, application/json, was not found
     at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
     at com.sun.jersey.api.client.Client.handle(Client.java:652)
     at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
     at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
     at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
     at com.graphhopper.api.vrp.client.ApiClient.getAPIResponse(ApiClient.java:470)
     at com.graphhopper.api.vrp.client.ApiClient.invokeAPI(ApiClient.java:517)
     at com.graphhopper.api.vrp.client.api.VrpApi.postVrp(VrpApi.java:88)
     at myapp.MapsActivity.start(MapsActivity.java:171)
     at myapp.MapsActivity.access$000(MapsActivity.java:44)
     at myapp.MapsActivity$1.run(MapsActivity.java:89)
 Caused by: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.lang.String, and MIME media type, application/json, was not found
     at com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter.java:288)
     at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:217)
     at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
 	... 10 more
```

**Comment by farmazon3000** [comment]
It may be related to #8.

**Comment by karussell** [comment]
Yes, this is caused as you exclude it here:
`exclude 'META-INF/services/javax.ws.rs.ext.MessageBodyWriter'`
